website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from flask import current_app
from .models import Event, Zusage
from . import db
import json
from datetime import datetime

# Erstellen eines Blueprint, einer Art Unteranwendung für Flask
views = Blueprint('views', __name__)

# Route für die Startseite, reagiert auf GET- und POST-Anfragen
@views.route('/', methods=['GET', 'POST'])
@login_required #home nur aufrufbar wenn eingeloggt
def home():
    # Überprüfen, ob die Anfrage vom Typ POST ist (Formulardaten gesendet)
    if request.method == 'POST':
        # Daten aus dem Formular extrahieren
        event_type = request.form.get('event_type')
        event_time = request.form.get('event_time')
        location = request.form.get('location')
        description = request.form.get('description')

        # Überprüfen, ob alle Formularfelder ausgefüllt sind
        if not event_type or not event_time or not location or not description:
            flash('Bitte füllen Sie alle Felder aus!', category='error')
        else:
            try:
                # Erstellen eines neuen Event-Objekts und Speichern in der Datenbank
                new_event = Event(
                    event_type=event_type,
                    description=description,
                    event_time=datetime.strptime(event_time, '%Y-%m-%dT%H:%M'),
                    location=location,
                    user_id=current_user.id
                )
                db.session.add(new_event)
                db.session.commit()
                flash('Event hinzugefügt!', category='success')
            except ValueError:
                flash('Falsches Datumsformat!', category='error')

    # Render des Home-Templates (HTML-Seite)
    return render_template("home.html", current_user=current_user)

# Route für die Übersichtsseite
@views.route('/uebersicht')
@login_required
def uebersicht():
    # Hier nehmen wir an, dass `current_user.events` die Events enthält, die dem Spieler angezeigt werden sollen
    events = current_user.events
    # Render des Übersichts-Templates (HTML-Seite)
    return render_template("events.html", events=events)

# Route für die Verarbeitung von Zusagen und Absagen
@views.route('/event-response', methods=['POST'])
@login_required
def event_response():
    # Daten aus der AJAX-Anfrage extrahieren
    data = request.get_json()
    event_id = data['event_id']
    status = data['response']  # 'zusage' oder 'absage'

    # Suchen Sie nach einer vorhandenen Zusage/Absage für dieses Event vom aktuellen Benutzer
    existing_response = Zusage.query.filter_by(user_id=current_user.id, event_id=event_id).first()

    # Wenn keine Antwort existiert, erstelle eine neue; andernfalls aktualisiere die existierende
    if not existing_response:
        new_response = Zusage(user_id=current_user.id, event_id=event_id, status=status)
        db.session.add(new_response)
    else:
        existing_response.status = status

    # Änderungen in der Datenbank speichern
    db.session.commit()

    flash(f"Du hast {'zugesagt' if status == 'zusage' else 'abgesagt'}!", category='success')
    return "ok"

# Route zum Löschen von Events
@views.route('/delete-event', methods=['POST'])
def delete_event():
    # Daten aus der AJAX-Anfrage extrahieren
    event = json.loads(request.data)
    eventId = event['eventId']

    # Event suchen und löschen, falls es dem aktuellen Benutzer gehört
    event = Event.query.get(eventId)
    if event:
        if event.user_id == current_user.id:
            db.session.delete(event)
            db.session.commit()

    # Leere JSON-Antwort senden
    return jsonify({}) ##empty response
    

website/templates/base.html
<!DOCTYPE html>
<main>
<head>
    <!-- Meta-Tags für Zeichensatz und Ansichts-Port-Einstellungen -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <!-- Einbindung des Bootstrap CSS Frameworks für Styling -->
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  />

  <!-- Einbindung eines benutzerdefinierten Stylesheets -->
  <link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}">

  <!-- Titel des Dokuments, der in den Browser-Tabs angezeigt wird -->
  <title>{% block title %}Home{% endblock %}</title>
</head>


<body> <!--Hauptteil des HTML-Dokuments-->
  <!-- Navigation (Navbar) für die Webseite mit Bootstrap-Styling -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <!-- Button für mobile Ansicht -->
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Navigationslinks -->
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav"> 
            <!-- Bedingungen, um Links basierend auf dem Authentifizierungsstatus anzuzeigen -->
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" id="home" href="/">Home</a>
            <a class="nav-item nav-link" id="uebersicht" href="{{ url_for('views.uebersicht') }}">Planübersicht</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            {% else %}
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
            <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
            {% endif %}
          </div>
        </div>
      </nav>
  
      <!-- Abschnitt für Flash-Nachrichten, die Benachrichtigungen anzeigen -->
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %} {% if category ==
      'error' %}
      
      <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% else %}

      <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %} {% endfor %} {% endif %} {% endwith %}
      
      <!-- Hauptinhalt der Seite, der von anderen HTML-Vorlagen gefüllt wird -->
      <div class="container">{% block content %} {% endblock %}</div>

      <!-- Einbindung von JavaScript-Bibliotheken für Funktionalität und Animation -->
      <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
      ></script>
  
      <!-- JavaScript-Block für zusätzliche Funktionalität, z.B. das Löschen von Events -->
  {% block javascript %}
      <script type="text/javascript">
        function deleteEvent(eventId) {
    fetch("/delete-event", {
      method: "POST",
      body: JSON.stringify({ eventId: eventId }),
    }).then((_res) => {
      window.location.href = "/";
    });
    }
  </script>
  {% endblock %}
    </body>
</html>

website/templates/events.html
{% extends "base.html" %}
{% block title %}Spielerübersicht{% endblock %}

{% block content %}


<h1 class="main-header">Planübersicht</h1>
<!-- Liste der Events -->
<ul class="list-group">
  <!-- Schleife über jedes Event, das dem Benutzer zugeordnet ist -->
  {% for event in events %}
  <li class="list-group-item">
    <!-- Anzeigen von Event-Details: Typ, Beschreibung, Zeit und Ort -->
    <h3>{{ event.event_type }}</h3>
    <p>Beschreibung: {{ event.description }}</p>
    <p>Zeit: {{ event.event_time.strftime('%d.%m.%Y %H:%M') }}</p>
    <p>Treffpunkt: {{ event.location }}</p>

    <!-- Logik zur Bestimmung der Farben der Buttons basierend auf der Zusage/Absage -->
    {% set green_class = '' %}
    {% set red_class = '' %}
    {% if event.zusagen | length >0 %}
    {% if event.zusagen[0].status == "zusage"%}
    {% set green_class = "green" %}
    {% else %}
    {% set red_class = "red" %}
    {% endif %}
    {% endif %}

    <!-- Buttons zum Senden einer Zusage oder Absage -->
    <button onclick="sendResponse('{{ event.id }}', 'zusage')" class="{{green_class}}">Zusage</button>
    <button onclick="sendResponse('{{ event.id }}', 'absage')" class="{{red_class}}">Absage</button>
  </li>
  {% endfor %}
</ul>
{% endblock %}

{% block javascript %}
<!-- JavaScript-Funktion zum Senden der Zusage/Absage zum Server -->
<script>
  function sendResponse(eventId, response) {
    fetch('/event-response', {
      method: 'POST',
      body: JSON.stringify({
        event_id: eventId,
        response: response
      }),
      headers: {
        'Content-Type': 'application/json'
      }
    })
      .then(response => {
        if (!response.ok) {
          console.error('Fehler: Netzwerkantwort war nicht ok.');
        } else {
          window.location.reload(true);
        }
      })
  }
</script>
{% endblock %}

website/templates/home.html
    {% extends "base.html" %}
    {% block title %}Übersicht{% endblock %}

    {% block content %}
    <h1 class="main-header">Event eintragen</h1>

    <!-- Liste der Events, die dem aktuellen Benutzer zugeordnet sind -->
    <ul class="list-group list-group-flush" id="events">
        <!-- Schleife über jedes Event in der Liste des aktuellen Benutzers -->
        {% for event in current_user.events %}
        <li class="list-group-item">
            {{ event.event_type }} - {{ event.description }} - {{ event.event_time.strftime('%Y-%m-%d %H:%M') }} - {{
            event.location }}
            <button type="button" class="close" onclick="deleteEvent('{{ event.id }}')">
                <span aria-hidden="true">&times;</span>
            </button>
        
        </li>
        {% endfor %}
    </ul>

    <!-- Bedingung, die überprüft, ob der aktuelle Benutzer ein Trainer ist -->
    {% if current_user.is_trainer() %}
    <!-- Formular zum Hinzufügen neuer Events -->
    <form method="POST">
        <!-- Auswahl des Event-Typs -->
        <div class="mb-4">
            <label for="eventType">Art des Events:</label>
            <select class="form-control" id="eventType" name="event_type">
                <option value="Training">Training</option>
                <option value="Match">Match</option>
            </select>
        </div>

        <!-- Eingabefeld für die Beschreibung des Events -->
        <div class="mb-4">
            <label for="eventDescription">Beschreibung</label>
            <textarea name="description" class="form-control" id="eventDescription" cols="30" rows="2"></textarea>
        </div>

        <!-- Eingabefeld für die Zeit des Events -->
        <div class="mb-4">
            <label for="eventTime">Zeit:</label>
            <input type="datetime-local" class="form-control" id="eventTime" name="event_time">
        </div>

        <!-- Eingabefeld für den Treffpunkt des Events -->
        <div class="mb-4">
            <label for="location">Treffpunkt:</label>
            <input type="text" class="form-control" id="location" name="location">
        </div>
        
        <!-- Button zum Absenden des Formulars -->
        <div align="center">
            <button type="submit" class="btn btn-primary">Füge das Event hinzu</button>
        </div>
    </form>
    {% endif %}

    <!-- Link zur Planübersicht-Seite -->
    <a href="{{ url_for('views.uebersicht') }}" class="btn btn-info">Zur Planübersicht</a>


    {% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}

{% block content %} 
<!-- Beginn des HTML-Formulars für die Anmeldung -->
<form method="POST">
    <h3 align="center">Login</h3>

    <!-- Formularfeld für die E-Mail-Adresse -->
    <div class="form-group">
        <label for="email">Email Adress</label>
        <input 
        type="email" 
        class="form-control" 
        id="email" 
        name="email" 
        placeholder="Enter email"
        />
    </div>

    <!-- Formularfeld für das Passwort -->
    <div class="form-group">
        <label for="password">Password</label>
        <input 
        type="password" 
        class="form-control" 
        id="password" 
        name="password" 
        placeholder="Enter password"
        />
    </div>

    <br />
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block content %} 

<!-- Beginn des HTML-Formulars für die Registrierung eines neuen Benutzers -->
<form method="POST">
    <h3 align="center">Sign Up</h3> <!-- Überschrift des Formulars -->

    <!-- Formularfeld für die E-Mail-Adresse -->
    <div class="form-group">
        <label for="email">Email Adress</label>
        <input 
        type="email" 
        class="form-control" 
        id="email" 
        name="email" 
        placeholder="Enter email"
        />
    </div>

    <!-- Formularfeld für den Vornamen-->
    <div class="form-group">
        <label for="name">Name</label>
        <input 
        type="text" 
        class="form-control" 
        id="Name" 
        name="Name" 
        placeholder="Enter name"
        />
    </div>

    <!-- Formularfeld für die Rolle-->
    <div class="form-group">
        <label for="role">Rolle</label>
        <input 
        type="text" 
        class="form-control" 
        id="role" 
        name="role" 
        placeholder="player oder trainer"
        />
    </div>

    <!-- Formularfeld für das Passwort-->
    <div class="form-group">
        <label for="password1">Password</label>
        <input 
        type="password" 
        class="form-control" 
        id="password1" 
        name="password1" 
        placeholder="Enter password"
        />
    </div>

    <!-- Formularfeld für den Passwort (bestätigen)-->
    <div class="form-group">
        <label for="password1">Password (Confirm)</label>
        <input 
        type="password" 
        class="form-control" 
        id="password2" 
        name="password2" 
        placeholder="Confirm password"
        />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button> 
</form>
{% endblock %}